Jagger: com.griddynamics.jagger.user.test.configurations.load.JLoadProfileRps.JLoadProfileRps
com.griddynamics.jagger.user.test.configurations.load.JLoadProfileRps.JLoadProfileRps (RequestsPerSecond requestsPerSecond, MaxLoadThreads maxLoadThreads, WarmUpTimeInSeconds warmUpTimeInSeconds)
Create load profile: request per seconds
.
Parameters
requestsPerSecond - The number of requests per second Jagger shall perform
maxLoadThreads - The maximum number of threads, which Jagger engine can create to provide the requested load
warmUpTimeInSeconds - The warm up time value in seconds. Jagger increases load from 0 to requestPerSecond by warmUpTimeInSeconds
Definition at line 26 of file JLoadProfileRps.java.
References com.griddynamics.jagger.user.test.configurations.load.aux.RequestsPerSecond.value(), com.griddynamics.jagger.user.test.configurations.load.aux.MaxLoadThreads.value(), and com.griddynamics.jagger.user.test.configurations.load.aux.WarmUpTimeInSeconds.value().
Referenced by com.griddynamics.jagger.user.test.configurations.load.JLoadProfileRps.of().
{
         Objects.nonNull(requestsPerSecond);
         Objects.nonNull(maxLoadThreads);
         Objects.nonNull(warmUpTimeInSeconds);
         this.requestsPerSecond = requestsPerSecond.value();
         this.maxLoadThreads = maxLoadThreads.value();
         this.warmUpTimeInSeconds = warmUpTimeInSeconds.value();
     }